export const ISSUING_BO_COLUMNS = [
  "session_id",
  "bo_oper_id",
  "ep_sttl_date",
  "run_date",
  "trx_type",
  "message_type",
  "contract_type",
  "card_number",
  "account_number",
  "sender_account_number",
  "auth_code",
  "arn",
  "trans_date",
  "sttl_amount",
  "st_rev",
  "merchant_name",
  "merchant_country",
  "transaction_date",
  "reversal_flag",
  "auth_message_type",
  "utrnno",
  "rrn",
] as const;

